Feature/msk21 qas 3 create slider component
egorka13/simple-ui-project pull request #10
Opened 2021-07-10 17:55 UTC by W014ara

Компонент слайдера (ползунка), практически аналогичный компоненту https://ant.design/components/slider/
Имеет возможность устанавливать параметры минимального, текущего, максимального значений, демонстрировать их под слайдером. Текущее значение демонстрируется маркером при наведении или нажатии на слайдер (уже добавил на страницу со всеми компонентами, так что можно посмотреть, запустив проект).
Имеется возможность добавления названия слайдера (легенды), а также настройка цвета полосы прогресса.

2021-07-11 18:34 UTC, alexpomazan submitted a review, later dismissed

2021-07-11 20:59 UTC, egorka13 requested changes

2021-07-11 20:59 UTC, egorka13 commented on src/app/library/components/slider/slider.component.html
> +        step="{{ step }}"
Пожалуйста, используй property binding syntax вместо интерполяции
`
[min]="minValue"
[max]="maxValue"
[value]="currentValue"
[step]="step"
`

2021-07-11 20:59 UTC, egorka13 commented on src/app/library/components/slider/slider.component.html
> +        disabled="{{ disabled }}"
`[disabled]="disabled"`

2021-07-11 20:59 UTC, egorka13 commented on src/app/library/components/slider/slider.component.ts
> +    customparams?: suiSliderParams;
Camel case

2021-07-11 21:02 UTC, egorka13 commented
Молодец! Интересный и функциональный компонент получился!

2021-07-11 21:10 UTC, egorka13 requested changes

2021-07-11 21:10 UTC, egorka13 commented on src/app/library/components/slider/slider.component.html
> +        <label for="sui-slider">{{ currentValue }}</label>
В данном файле нет элемента с `id='sui-slider'`

2021-07-12 13:11 UTC, W014ara commented
Сделал фикс недочетов

2021-07-12 13:42 UTC, egorka13 approved these changes

2021-07-12 13:42 UTC, merged