Feature/msk21 qas 10 create card component
egorka13/simple-ui-project pull request #11
Opened 2021-07-11 18:27 UTC by alexpomazan

2021-07-11 18:29 UTC, alexpomazan commented
Похоже я не очень правильно merge сделал) Очень много коммитов. Поэтому лучше делать rebase?

2021-07-11 20:40 UTC, izotarina commented on src/app/library/components/card/card.component.less
> +                    color: lib-blue-light;
Забыл знак @

2021-07-11 20:47 UTC, izotarina requested changes

2021-07-11 20:47 UTC, izotarina commented on src/app/library/components/card/card.component.less
> +                    color: lib-blue-light;
Пропустил знак @

2021-07-11 20:47 UTC, izotarina commented on src/app/library/components/card/card.component.less
> +        &._small > .sui-card__header{
По БЭМу модификаторы либо булевые, либо имеют вид ключ-значение. В данном случае _size_small

2021-07-11 21:22 UTC, egorka13 requested changes
Попробуй добавить новый @Input, дающий возможность добавлять custom template в области контента и отображать его там

2021-07-12 13:34 UTC, izotarina approved these changes

2021-07-12 13:38 UTC, egorka13 approved these changes

2021-07-12 13:38 UTC, merged