Added board dragging logic.
egorka13/simple-ui-project pull request #13
Opened 2021-07-13 16:05 UTC by taratatuy

Промежуточные изменения в компоненте. 
Добавил функционал для перетаскивания доски при зажатом пробеле и возвращение на исходную позицию двойным кликом.
Дальше буду делать настройки доски (зум, указание ширины и высоты) и сервис, который дергать, чтобы их изменять.

2021-07-14 04:50 UTC, taratatuy commented
Реализовал зум доски и вынес его логику в отдельный сервис.

2021-07-14 05:02 UTC, taratatuy commented on src/app/components/board/board.component.html
> +    "
Напрягает это место. По сути это `` `scale(${ <...> }) translate(${ <...> }px, ${ <...> }px)` ``, однако обратные кавычки `` ` ` `` не работают внутри шаблона. Если убрать составную строку из шаблона и объявить ее в переменной внутри контроллера, данная переменная не будет реактивно обновляться при изменении какой-либо из внутренних переменных. Возможно, надо использовать вотчер или еще какой-то встроенный функционал в ангуляре?

2021-07-14 07:12 UTC, taratatuy commented on src/app/core/services/board-settings.service.ts
> +import { IPoint } from 'src/app/components/board/board.model';
Также вопрос с путями. Положил board.model.ts в папку компоненты. Как их лучше писать, если в сервисе понадобился интерфейс?

2021-07-14 22:51 UTC, taratatuy commented
Добавил в сервис настройку ширины и высоты доски.

2021-07-15 09:23 UTC, izotarina approved these changes, later dismissed

2021-07-15 09:49 UTC, egorka13 commented on src/app/components/board/board.component.html
> +    "
А что если попробовать вынести в переменную, но сделать её Subject
Тогда изменения этой переменной необходимо будет прокидывать из любого места через .next() метод
А в шаблоне необходимо подписаться на эту переменную - `[style.transform]="boardSettingsService.transformStyle$ | async"`

2021-07-15 09:53 UTC, egorka13 commented on src/app/core/services/board-settings.service.ts
> +import { IPoint } from 'src/app/components/board/board.model';
В целом можно и просто так было оставить:
`import { IPoint } from '../../components/board/board.model';`

Либо есть еще возможность добавлять alias в angular
Для этого внутри tsconfig.json необходимо добавить такую запись:
`
"paths": {
      "@components/*": ["app/components/*"]
    }
`

2021-07-15 11:48 UTC, egorka13 commented
Заметил такую багу при попытке зумить с помощью тачпада (2 пальца на тачпаде и перемещал их вверх, например)
![image](https://user-images.githubusercontent.com/23345465/125783086-5c3a3672-ef3c-43e1-b120-f8a41a1cb87c.png)

2021-07-15 15:31 UTC, taratatuy commented
Данный баг появлялся при горизонтальном скролле, т.к. данный скролл смещает по вертикали на 0, что передается в функцию изменения размера, и при делении на 0 возникает NaN.

2021-07-16 07:45 UTC, egorka13 requested changes
Дожидаюсь изменений с pipe для [style.transform] и мержу

2021-07-16 07:58 UTC, taratatuy commented
1. Изменил пути на ярлыки.
2. Переделал передачу стилей в трансформ доски. Отказался от создания пайпа, сделал, как ты советовал выше, через rxjs. Обоснованно это тем, что так возвращаемая строка инкапсулирована вместе с остальной логикой по этим стилям и не нужно знать внутреннее устройство и как этим пайпом и пользоваться внутри шаблона.
3. Перенес логику зума с колесика мыши на него же, но только с зажатым контролом. Чтобы это не конфликтовало с нативным браузерным масштабированием страницы добавил превент. Работает в хроме и эдже, в остальных браузерах не тестил.

2021-07-16 08:00 UTC, egorka13 approved these changes, later dismissed

2021-07-16 08:07 UTC, egorka13 approved these changes, later dismissed

2021-07-16 08:14 UTC, izotarina approved these changes

2021-07-16 08:26 UTC, egorka13 approved these changes

2021-07-16 08:26 UTC, merged