Feature/msk21 qas 13 create header component
egorka13/simple-ui-project pull request #16
Opened 2021-07-27 14:39 UTC by W014ara

Компонента, ответственная за работу шапки сайта. Имеет возможность изменять скейл центрального холста, его размеры, включать/отключать сетку, а также имеется возможность перехода на url страницы просмотра всех компонент библиотеки.

2021-07-27 15:46 UTC, alexpomazan commented
В пулл реквесте получается и моя ветка, но я немного еще исправлю свои стили и запушу после этого мерджа.

2021-07-27 16:29 UTC, taratatuy requested changes

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/component-panel/component-panel.component.ts
> +    public test:string = "1";
Поле еще актуально?)

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/component-panel/popup/popup.component.ts
> +import { LibraryGetterService } from '../../../core/services/library-getter.service';
`../../../core/services/library-getter.service` стоит заменить на `@services/library-getter.service`

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/component-panel/popup/popup.component.ts
> +import { ILibraryInformation, IlibraryCurrentInformation } from '../../../core/services/library-getter.model';
Модель стоит перенести в папку _app/models/_ и импортировать через `@models/library-getter.model`.

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/header/grid/grid.component.ts
> +    ngOnInit(): void {}
`OnInit` не используется, можно его вообще удалить вместе с импортом и интерфейсом :)

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/header/header.component.ts
> +    ngOnInit(): void {}
Здесь также не используется `OnInit`, можно удалить метод, импорт и интерфейс.

2021-07-27 16:29 UTC, taratatuy commented on src/assets/styles/variables/colors.less
> +@sui-blue-1: hsl(209, 100%, 50%);
:D

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/board/board.component.less
> +            cursor: grab;
Такое ощущение, что здесь закоммичена старая версия этого файла стилей. Так подумал из-за того, что здесь удалены комментарии и передвинуто свойство курсора. Это сделано осознанно по какой-то причине?

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/board/board.component.ts
> +}
Кстати, гитхаб рисует минус в красном кружочке, это значит, что в конце файла не стоит перенос строки. Данная настройка отображается гитхабом, потому что он автоматически подтягивает наши проектные правила, указанные в файле .editorconfig. Чтобы среда тоже следовала данным правилам можно поставить одноименный [плагин](https://editorconfig.org/). Подробнее с editorconfig можно познакомиться, например, в [видео](https://www.youtube.com/watch?v=wWbDC1C7JEE) Вадима Макеева на эту тему.

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/component-panel/popup/popup.component.less
> +        padding:10px 10px 25px 10px;
По этому файлу стоит пройтись преттьером, где-то нет пробелов после `:`.

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/component-panel/panel.model.ts
> +}
Если этот файл используется еще в каких-то компонентах, его стоит перенести в папку _app/models/_ и импортировать через `@models/panel.model`.

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/component-panel/popup/popup.component.ts
> +    ngOnInit(): void {}
`OnInit` не используется, можно удалить метод и импорт.

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/component-panel/popup/popup.component.ts
> +        }, 100);
100ms указано здесь специально? Если таймаут используется здесь, чтобы подружить создание компоненты с ChangeDetector'ом, то, по идее, здесь должно хорошо работать с задержкой в 0ms.

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/header/grid/grid.model.ts
> +}
Этот файл с интерфейсом используется в сервисе _grid-setting_, его стоит перенести в папку _models_ и испортить через `@models/grid.model`.

2021-07-27 16:29 UTC, taratatuy commented on src/app/components/header/header.component.ts
> +import { GridSettingsService } from 'src/app/core/services/grid-settings.service';
Импорт сервисов стоит сделать через `@services/`.

2021-07-27 16:29 UTC, taratatuy commented on src/app/core/services/grid-settings.service.ts
> +import { IGridSettings } from '../../components/header/grid/grid.model';
Уже писал выше про эту модель. Перенести и поменять путь на `@models/`.

2021-07-27 16:29 UTC, taratatuy commented on src/app/core/services/grid-settings.service.ts
> +import { BoardSettingsService } from './board-settings.service';
Сервис также лучше импортировать через `@services/` несмотря на то, что они в одной папке.

2021-07-27 16:29 UTC, taratatuy commented on src/app/core/services/library-getter.service.ts
> +
Аналогично написанному выше. Вроде не принято отделять декораторы переносами строки, пусть Егор уточнит.

2021-07-27 16:29 UTC, taratatuy commented on src/app/core/services/grid-settings.service.ts
> +
Вроде не принято отделять декораторы переносом строки.

2021-07-27 16:49 UTC, taratatuy commented on src/app/core/services/board-settings.service.ts
> +    public setScale(value:number){
Потерял возвращаемый тип :) Стоит пройтись по всем файлам еслинтом.

2021-07-27 16:56 UTC, W014ara commented on src/app/components/board/board.component.less
> +            cursor: grab;
Не трогал там ничего, вроде как, может действительно какая-то старая версия.

2021-07-27 17:02 UTC, W014ara commented
@taratatuy я сделал фикс header'а, grid'а и все, что связано с ними. Компоненту component-panel я не стал рефакторить т.к. Леша закинет с ней свой пулл реквест и в дальнейшем я натяну логику попапа туда т.к. все еще довольно сыро. Та же тема с компонентом popup, он процентов на 50 сделан еще неверно.

2021-07-28 06:52 UTC, egorka13 commented on src/app/core/services/library-getter.service.ts
> +
Да, не принято, лучше писать без переносов

2021-07-28 07:08 UTC, egorka13 requested changes

2021-07-28 07:08 UTC, egorka13 commented on src/app/components/board/board.component.less
> +            cursor: grab;
Давайте может откатим тогда предыдущую версию?

2021-07-28 07:08 UTC, egorka13 commented on src/app/components/component-panel/component-panel.component.html
> +<div class="panel__wrapper">
Классы надо переименовать, чтобы они начинались с названия блока, в данном случае `sui-component-panel__?`

2021-07-28 07:08 UTC, egorka13 commented on src/app/components/component-panel/component-panel.component.less
> +.panel{
Аналогично класс должен называться `sui-component-panel`

2021-07-28 07:08 UTC, egorka13 commented on src/app/app.module.ts
> +import { PopupComponent } from './components/component-panel/popup/popup.component';
```
import { GridComponent } from '@components/header/grid/grid.component';
import { PopupComponent } from '@components/component-panel/popup/popup.component';
```

2021-07-28 07:08 UTC, egorka13 commented on src/app/components/component-panel/component-panel.component.ts
> +    public showPopup(item: IlibraryCurrentInformation, event: Event):void{
Этот метод можно отформатировать получше, где-то не хватает отступов, где-то наоборот лишние

2021-07-28 07:08 UTC, egorka13 commented on src/app/components/header/header.component.html
> +                <input (change)="onChangeInput($event)" (click)="onClickInput($event)" (keyup)="onKeyUpInput($event)" type="text" class="sui-header__navigation-zoomInput" value="{{getRounderScale()}}
Кстати когда много атрибутов и слушателей событий на элементе - их лучше располагать с новый строки каждый (а лучше даже так делать всегда, потому что это более читаемо)

2021-07-28 07:08 UTC, egorka13 commented on src/app/components/header/header.component.html
> +            <input class="sui-header__boardSettings-setting" [(ngModel)]="boardSettingsService.width" placeholder="Board width" title="Change board's width">
Тут тоже самое, строчки слишком длинными стали

2021-07-28 07:08 UTC, egorka13 commented on src/app/models/grid.model.ts
> +    strokeWidth:number;
Пробелы

2021-07-28 07:08 UTC, egorka13 commented on src/app/models/library-getter.model.ts
> +    desciption:string;
Пробелы и отступы

2021-07-28 12:36 UTC, W014ara commented
Отрефакторил свои компоненты

2021-07-28 12:37 UTC, egorka13 commented on src/app/components/component-panel/component-panel.component.less
> +.panel{
@alexpomazan поправь пожалуйста потом у себя в ветке

2021-07-28 12:38 UTC, egorka13 commented on src/app/components/component-panel/component-panel.component.html
> +<div class="panel__wrapper">
@alexpomazan поправь потом пожалуйста у себя в ветке

2021-07-28 12:38 UTC, egorka13 commented
> Отрефакторил свои компоненты

А стили для board.component.less удалось откатить?

2021-07-28 12:53 UTC, W014ara commented
@egorka13 откатил изменения, такие же как и в dev, так и в ветке Саши. Единственное, я добавил на showcases relative и z-index, чтобы сетка не перебивала собой контент на холсте

2021-07-28 14:07 UTC, egorka13 approved these changes

2021-07-28 14:09 UTC, taratatuy approved these changes

2021-07-28 14:14 UTC, merged