Feature/msk21 qas 7 create result component
egorka13/simple-ui-project pull request #2
Opened 2021-07-06 14:32 UTC by W014ara

Компонента аналогична _https://ant.design/components/result/_
1) Имеется возможность изменять тип компоненты (по сути, изменение главной картинки. Предусмотрены все варианты, как на страничке с компонентой, так и добавление собственной картинки через текстовое описание пути до картинки)
2) Имеется возможность добавлять и настраивать заголовок и подзаголовок (текст, шрифт, цвет, размер)
3) Имеется возможность настраивать кнопки компоненты (внутренняя ссылка, текст, фон, обводка. Единственное - при изменении стандартных стилей компоненты, пропадают эффекты с hover'ами и другими. Не знаю, насколько это критично)

Настройка компоненты осуществляется через передачу _**массива строковых параметров**_ (в файле result.component.ts вроде как описал все расширенными комментариями)

2021-07-06 14:50 UTC, egorka13 commented
@W014ara, на файлы, связанные со слайдером пока не обращать внимания?

2021-07-06 15:37 UTC, egorka13 requested changes

2021-07-06 15:37 UTC, egorka13 commented on src/app/library/components/sui-result/result.component.ts
> +    generalBtnEdentifier: ElementRef;
generalBtnIdentifier

2021-07-06 15:37 UTC, egorka13 commented on src/app/library/components/sui-result/result.component.ts
> +    additionalBtnEdentifier: ElementRef;
additionalBtnIdentifier

2021-07-06 15:37 UTC, egorka13 commented on src/app/library/components/sui-result/result.component.less
> +            box-sui-resultC-shadow: @sui-resultC-shadow;
ошибочное свойство

2021-07-06 15:37 UTC, egorka13 commented on src/app/library/components/sui-result/result.component.less
> +            border-color: @sui-resultC-additionalBorder;
border-color просто перезаписывает transparent в свойстве border, определенном выше
Может его сразу там задавать, как @sui-resultC-additionalBorder?

2021-07-06 15:37 UTC, egorka13 commented on tsconfig.json
> +        "strictPropertyInitialization": false,
👍

2021-07-06 15:37 UTC, egorka13 commented on src/app/library/components/sui-result/result.component.ts
> +            const fontSize = data[3];
не хватает типов для заданных переменных

2021-07-06 17:05 UTC, W014ara commented
пофиксил указанные недочеты

2021-07-06 18:41 UTC, W014ara commented on src/app/library/components/sui-result/result.component.ts
> +            const fontSize = data[3];
пофиксил

2021-07-06 18:41 UTC, W014ara commented on src/app/library/components/sui-result/result.component.less
> +            border-color: @sui-resultC-additionalBorder;
пофиксил, сразу задал параметр. Неудачно скопировал видимо стили с анта

2021-07-06 18:42 UTC, W014ara commented on src/app/library/components/sui-result/result.component.less
> +            box-sui-resultC-shadow: @sui-resultC-shadow;
при рефакторе переменных видимо кусок переименовался. Пофиксил

2021-07-07 08:50 UTC, egorka13 submitted a review, later dismissed

2021-07-07 15:14 UTC, egorka13 submitted a review, later dismissed

2021-07-07 17:00 UTC, egorka13 approved these changes

2021-07-07 18:31 UTC, alexpomazan approved these changes

2021-07-07 18:31 UTC, alexpomazan commented on src/app/library/components/sui-result/result.component.html
> +<div class="sui-result">
Лишний div, на уроке решили же задавать стили блоку компоненты, а '.sui-result' в less оставлять пустым.

2021-07-07 19:12 UTC, W014ara commented on src/app/library/components/sui-result/result.component.html
> +<div class="sui-result">
Не особо понял, что требуется сделать, у меня если компоненту не обернуть во внешний блок внутренний div на всю ширину растянется

2021-07-08 06:23 UTC, merged