Feature/msk21 qas 19 create component preview for component panel
egorka13/simple-ui-project pull request #21
Opened 2021-08-01 14:18 UTC by W014ara

**Компонента подсказки (всплывающее окно)** при наведении на любую из компонент в левом списке.
Имеется возможность перестройки позиции, если видимый контент заходит за нижнюю границу видимой части экрана.
Помимо этого, **отредактировал сервис LibraryGetterService.** Теперь там хранятся все компоненты с общей информацией. На основе этого, переделал логику компоненты ComponentPanelComponent. Конкретно - теперь все категории и компонениы автоматически парсятся из сервиса LibraryGetterService. 

**Комментарии к методам и полям ComponentPanelComponent оставил только для своих.** Леша может добавить, если необходимо новые комментарии к своему коду, для большей документации

**Для регистрации новых компонент** достаточно добавить новое поле в libraryInformation. Для регистрации новой категории - добавить новое поле в deferTypes (сервис LibraryGetterService) и в модель library-getter.model.ts

Помимо этого - **отрефакторил немного сервис отрисовки сетки** (конкретно отписку от слежения за изменением окна board'а). _Исправить блюр не получилось_, я честно не знаю, в чем вообще проблема, изменение размера полотна с учетом scale, dpi экрана не вариант :shrug: . Делать анимацию через requestAnimationFrame тоже не получается (эффект тот же самый).

2021-08-02 16:05 UTC, egorka13 requested changes

2021-08-02 16:05 UTC, egorka13 commented on src/app/components/header/grid/grid.component.less
> -
Здесь наоборот должны быть пробелы

2021-08-02 16:05 UTC, egorka13 commented on src/app/core/services/library-getter.service.ts
> +import { SliderComponent } from '../../library/components/slider/slider.component';
Здесь тоже желательно оставить первый вариант с @

2021-08-02 16:05 UTC, egorka13 commented on src/app/library/components/radio/radio.component.less
> -
Перенос строки тут нужен

2021-08-02 17:39 UTC, W014ara commented
@egorka13 пофиксил

2021-08-02 21:32 UTC, egorka13 submitted a review, later dismissed

2021-08-03 10:13 UTC, taratatuy requested changes

2021-08-03 10:13 UTC, taratatuy commented on src/app/components/header/grid/grid.component.less
> +    z-index: 1;
Напомни, зачем сетке _z-index: 1_? Если сейчас закоммитить это в дев, компоненты не получится перемещать. Скорее всего, я в ближайшее время немного изменю положение сетки в разметке доски, так что задавать ей _z-index_ совсем не понадобится, но пока лучше оставить -1, чтобы дев не ломался.

2021-08-03 10:13 UTC, taratatuy commented on src/app/core/services/grid-settings.service.ts
> +            this.stopGridSubscribe();
Насколько я понял, если включить грид, а потом, не выключая, уйти на страницу _/lib_, то подписка так и останется. Стоит добавить отписку в _ngOnDestroy_ тоже.

2021-08-03 10:15 UTC, taratatuy commented
Также у тебя закоммичен файл _src/app/components/.gitkeep_. Он был нужен, когда папка была пустая. Теперь он не нужен.

2021-08-03 10:41 UTC, egorka13 commented
@W014ara можешь еще откатить пожалуйста файл radio.component.less, так как у тебя в нем убраны все пробелы, а они нужны

2021-08-03 10:53 UTC, W014ara commented on src/app/components/header/grid/grid.component.less
> +    z-index: 1;
Делал это из-за того, что canvas перекрывает все элементы на board'е, потому, т.к. board-item изначально вставлялся в
.sui-board__field-showcases, там стоял z-index, как и у canvas. Сейчас, как я вижу board-item вставляется вне этого блока. Можно добавить z-index: 2 елементу и на него можно будет кликать.
Если положение сетки и стили поменяются еще, то ок, но на текущем этапе z-index был как раз, чтобы сетка не была выше других элементов board'а.

2021-08-03 10:59 UTC, W014ara commented
@egorka13 забрал стили из dev ветки, они же, как я понимаю, те, которые необходимы?
@taratatuy  добавил ngOnDestroy

2021-08-03 11:10 UTC, taratatuy commented on src/app/components/header/grid/grid.component.less
> +    z-index: 1;
_z-index: -1_ гарантированно поставит ее ниже всех элементов, разве нет?

2021-08-03 11:16 UTC, W014ara commented on src/app/components/header/grid/grid.component.less
> +    z-index: 1;
Да, поставил -1

2021-08-03 11:22 UTC, taratatuy approved these changes, later dismissed

2021-08-03 13:26 UTC, egorka13 commented
> @egorka13 забрал стили из dev ветки, они же, как я понимаю, те, которые необходимы?

Да, в деве было то, что нужно

2021-08-03 13:27 UTC, egorka13 approved these changes

2021-08-03 13:28 UTC, merged