Feature/msk21 qas 31 create switch component
egorka13/simple-ui-project pull request #24
Opened 2021-08-05 21:04 UTC by W014ara

Компонента - аналог https://ant.design/components/switch/
Имеется возможность следующих настроек:

1) Вставка текста на checked и не checked состояния
2) Вставка галочки и крестика в соответствующих состояниях (или комбинирования этих иконок вместе с текстом)
3) Имеется возможность поставить loading картинку если кнопка в состоянии disabled

Для перехвата состояния добавлен EventEmitter
Компонента уже **зарегистрирована в левой панели**, однако **настройки с правой панели** для нее пока **не работают** т.к. нет конфигурации в файле config-panel.model.ts

2021-08-07 16:33 UTC, taratatuy requested changes

2021-08-07 16:33 UTC, taratatuy commented on src/app/library/components/switch/switch.component.html
> +            'sui-switch__item': true,
Если этот класс всегда навешен, его можно перенести в обычный атрибут _class="sui-switch__item"_.

2021-08-07 16:33 UTC, taratatuy commented on src/app/library/components/switch/switch.component.ts
> +    innerText?: Array<string>;
Стоит разбить этот параметр на два: один - enabled state text, второй - disabled state text. Так будет понятнее изменение их в правой панели (будут два отдельных свойства, для каждого состояния свое). Также, можно избавиться от функции _checkInnerText_ задав дефолтные значения = ''.

2021-08-07 16:33 UTC, taratatuy commented on src/app/library/components/switch/switch.component.ts
> +    public text: string;
Насколько я понял, поле _text_ изменяется согласно внутренней логике, просто так извне присваивать значение в него не положено. Если это так, и _text_ публичная, только ради доступа к этому полю из шаблона, тогда стоит переименовать его в __text_ (подчеркивание в начале).

2021-08-07 16:33 UTC, taratatuy commented on src/app/library/components/switch/switch.component.ts
> +    public markerPath: string = resultTypes.off;
Аналогично полю _text_, поле _markerPath_ стоит переименовать в __markerPath_, поскольку не предполагается изменение его извне этой компоненты.

2021-08-07 16:33 UTC, taratatuy commented on src/app/library/components/switch/switch.component.ts
> +    }
Сейчас это хорошо работает на клик по компоненте в интерактивном режиме, но если поменять поле _isChecked_  из правой панели, текст не поменяется. Я бы вынес логику из _onClick()_ в приватную функцию и запускал ее из _onClick()_ и из сеттеров для полей _isChecked_, _useMarkers_ и полей, связанных с текстом.

2021-08-07 16:33 UTC, taratatuy commented on src/app/library/components/switch/switch.model.ts
> +    off: path + 'off.svg',
Это не ошибка, но как будто реализовать это на css и навешивать анимашку и состояние через классы было бы проще :D

2021-08-07 16:33 UTC, taratatuy commented on src/app/library/components/switch/switch.component.html
> +                src="app/library/assets/icons/switch/load.svg"
Не уверен, что правильно хардкодить путь в шаблон, может, стоит его вынести в модель или контроллер, как ты делал это ниже?

2021-08-07 16:33 UTC, taratatuy commented on src/app/library/components/switch/switch.model.ts
> +}
Такой интерфейс не несет особого смысла, потому что не задает обязательных полей и может принимать любые поля. По сути, под этот интерфейс подходит любой объект.
Он используется ниже для _resultTypes_, и, наверно, должен определять два поля: _on: string_ и _off: string_.

2021-08-07 16:33 UTC, taratatuy commented on src/app/library/components/switch/switch.component.less
> +}
Анимация линейная, можно удалить объявления промежуточных состояний, оставить только 0% и 100%.

2021-08-07 16:33 UTC, taratatuy commented on src/app/library/components/switch/switch.component.ts
> +     * IAn input parameter responsible for putting the component in an inactive state.
```suggestion
     * An input parameter responsible for putting the component in an inactive state.
```
Очипятка.

2021-08-09 09:47 UTC, egorka13 submitted a review, later dismissed
Апрув после исправления замечаний Саши

2021-08-09 19:31 UTC, egorka13 submitted a review, later dismissed

2021-08-10 08:04 UTC, egorka13 requested changes

2021-08-10 08:04 UTC, egorka13 commented on src/app/models/config-panel.model.ts
> +    'sui-switch': {},
Необходимо определить модель для корректной работы конфигурационной панели

2021-08-10 14:14 UTC, W014ara commented
@taratatuy подправил, вроде норм работает

2021-08-11 01:15 UTC, taratatuy requested changes

2021-08-11 01:15 UTC, taratatuy commented on src/app/library/components/switch/switch.component.ts
> +        console.log(this.checkedText, this.uncheckedText);
Стоит почистить консоль лог, чтобы в дев не попал.

2021-08-11 01:15 UTC, taratatuy commented on src/app/library/components/switch/switch.component.ts
> +    isChecked: boolean = false;
Сделай это поле сеттером и перенеси сюда логику из _onClick()_. Пока что __text_ и маркеры все еще не обновляются, если менять isChecked из конфигурационной панели.
[Видео с багом](https://user-images.githubusercontent.com/32226448/128954299-417b79d7-6673-4c46-a87b-a32b74868176.mp4).

2021-08-12 12:07 UTC, egorka13 approved these changes

2021-08-12 13:15 UTC, W014ara commented
@taratatuy ну на этот раз вроде всё 😃

2021-08-12 16:21 UTC, taratatuy approved these changes

2021-08-12 16:21 UTC, taratatuy commented on src/app/library/components/switch/switch.component.ts
> +    }
Если очень хочется улучшить код, то можно подтереть логику в этой функции, внутри нее написать вызов _this.setChecked(!this.checked)_, чтобы сеттер все за тебя сделал, и вызов эмиттера _this.switchStatus.emit(this.isChecked)_. Но я думаю, опять отправлять эту компоненту на доработку уже совсем немилосердно :D

2021-08-12 19:27 UTC, merged