Feature/msk21 qas 29 create library component link
egorka13/simple-ui-project pull request #26
Opened 2021-08-08 22:17 UTC by alexpomazan

Компонента ссылки. Можно изменять цвет текста, цвет при hover, текст, размер текста, а так же href.

2021-08-09 10:06 UTC, egorka13 approved these changes, later dismissed
Можешь пожалуйста добавить пример на странице showcases?

2021-08-09 10:51 UTC, W014ara commented on src/app/library/components/link/link.component.ts
> +    }
Не совсем понял, почему методы возвращают значение, которое вроде как нигде не больше не используется?

2021-08-09 14:57 UTC, alexpomazan commented on src/app/library/components/link/link.component.ts
> +    }
Это значение я записываю в [style.color]="color"

2021-08-09 21:34 UTC, egorka13 requested changes

2021-08-09 21:34 UTC, egorka13 commented on src/app/library/components/link/link.component.ts
> +    }
Но тут и вправду достаточно присваивания, возвращаемое значение не используется

2021-08-09 22:00 UTC, alexpomazan commented on src/app/library/components/link/link.component.ts
> +    }
А, понял)

2021-08-10 06:40 UTC, egorka13 submitted a review, later dismissed

2021-08-10 12:49 UTC, W014ara submitted a review, later dismissed

2021-08-10 12:53 UTC, egorka13 approved these changes

2021-08-10 12:53 UTC, merged