Feature/MSK21QAS-33 create alert component
egorka13/simple-ui-project pull request #27
Opened 2021-08-09 13:08 UTC by izotarina

Добавление компоненты alert:
1. Имеет 4 типа сообщений: success, info, warning, error.
2. Опционально может иметь поле описания.
3. Опционально может иметь иконку типа сообщения.
4. Иконка меняет свой размер в зависимости от наличия/отсутствия описания.
5. Модель компоненты добавлена в модель конфигурационной панели.
6. Компонента добавлена в library showcase.
7. Нет возможности добавить компоненту на доску, т.к. нет кнопки alert в панели компонентов.

2021-08-09 19:34 UTC, alexpomazan approved these changes, later dismissed

2021-08-09 21:38 UTC, egorka13 requested changes

2021-08-09 21:38 UTC, egorka13 commented on src/app/library/components/alert/alert.component.ts
> +    public icon: boolean = false;
Boolean переменные должны именоваться, начиная с is…
В данном случае icon отвечает за то, рисуется ли иконка или нет?

2021-08-10 06:56 UTC, egorka13 commented on src/app/library/components/alert/alert.component.ts
> +    public icon: boolean = false;
https://wiki.edu-netcracker.com/pages/viewpage.action?pageId=35459477

2021-08-10 08:00 UTC, egorka13 approved these changes

2021-08-10 08:00 UTC, merged