Feature/msk21 qas 13 create header component
egorka13/simple-ui-project pull request #28
Opened 2021-08-11 21:06 UTC by W014ara

Добавил кнопку работы интерактивного режима в шапку + изменил кнопку "remove item" на "clear board", однако логику не вешал на эту кнопку

2021-08-11 21:58 UTC, taratatuy commented
В эту ветку попали файлики из ветки со свитчем

2021-08-12 12:09 UTC, egorka13 commented
> В эту ветку попали файлики из ветки со свитчем.

Правильное замечание от Саши, это не совсем корректно, надо поправить
Видимо ты отпочковался от ветки со свитчем, а надо было от дева

2021-08-12 13:17 UTC, W014ara commented
@egorka13 
@taratatuy 
убрал switch, да, не с той ветки изменения подтянул, сейчас вроде изменения только по header'у

2021-08-12 13:20 UTC, egorka13 requested changes

2021-08-12 13:20 UTC, egorka13 commented on src/app/components/header/header.component.ts
> +    public interactiveState: boolean = false;
Boolean переменные должны именоваться, начиная с is…
Лучше назвать isInteractiveMode или аналогично

Можно и для gridState поменять тоже, например isGridShown

https://wiki.edu-netcracker.com/pages/viewpage.action?pageId=35459477 [6]

2021-08-12 13:27 UTC, W014ara commented
@egorka13 подправил

2021-08-12 16:38 UTC, taratatuy approved these changes

2021-08-12 19:28 UTC, egorka13 approved these changes

2021-08-12 19:28 UTC, merged