feature/MSK21QAS-5-create-button-component
egorka13/simple-ui-project pull request #4
Opened 2021-07-07 18:54 UTC by izotarina

Добавление компоненты Button.
Стили взяты из https://ant.design/components/button/

2021-07-07 19:31 UTC, taratatuy reviewed
Возможно, объединить содержимое файлов buttonSizes.ts и buttonTypes.ts в один файл button.model.ts.

2021-07-07 19:58 UTC, taratatuy reviewed
В стилях компоненты использованы цвета, которые обсуждали в телеграмме, по типу @lib-blue, но они не закоммичены в файлик colors.less. Думаю, можно их смержить, а старые цвета, которые были написаны, пока мы единогласно не договорились о нейминге, подтереть потом, по мере перехода остальных компонент на новые названия.
UPD: Предложил изменения в файл colors.less из своей ветки.

2021-07-08 06:34 UTC, izotarina commented
Объединила buttonSizes.ts и buttonTypes.ts в один файл button.model.ts.

2021-07-08 06:48 UTC, egorka13 requested changes

2021-07-08 06:48 UTC, egorka13 commented on src/app/library/components/button/button.component.html
> +    [ngClass]="getClasses()"
Если сделать getClasses геттером, то вызов здесь не будет нужен

2021-07-08 06:48 UTC, egorka13 commented on src/app/library/components/button/button.component.less
> +@font-size: 14px;
А можно это вынести в переменные?

2021-07-08 06:48 UTC, egorka13 commented on src/app/library/components/button/button.component.less
> +    background-color: #fff;
@lib-white не подойдет?

2021-07-08 06:48 UTC, egorka13 commented on src/app/library/components/button/button.component.ts
> +    getClasses(): string {
переделай, пожалуйста, в геттер

2021-07-08 07:20 UTC, egorka13 requested changes

2021-07-08 07:20 UTC, egorka13 commented on src/app/library/components/button/button.component.less
> +.button {
Просьба - поменять название класса с button на sui-button, потому что по логике у тебя селектор в ts файле назван, как sui-button и он же и будет являться для нас БЭМ-блоком, соответственно все дочерние элементы должны именоваться, как sui-button__element

2021-07-08 07:38 UTC, izotarina commented
Исправлены замечания.
Переменную font-size решила убрать, так как не знаю, будет ли она использоваться в других компонентах. Скорее всего размер будет задаваться пользователем.

2021-07-08 07:39 UTC, egorka13 approved these changes

2021-07-08 07:40 UTC, merged