Added checkbox component. Feature/MSK21QAS-4-create-checkbox-component
egorka13/simple-ui-project pull request #6
Opened 2021-07-07 21:59 UTC by taratatuy

Компонент аналогичен https://ant.design/components/checkbox/

2021-07-07 22:05 UTC, taratatuy commented on src/app/library/assets/styles/colors.less
> +@lib-disabled-bg: hsl(0deg, 0%, 96%); // #ebedf0
Закомментированное Hex значение не верно, будьте внимательны! Заметил позже и не стал делать отдельный коммит для исправления комментария. Исправлю, если будут другие ошибки.

2021-07-08 07:14 UTC, egorka13 requested changes
Единственная просьба - поменять название класс с checkbox на sui-checkbox, потому что по логике у тебя селектор назван, как sui-checkbox и по суть он же и будет являться для нас БЭМ-блоком, соответственно все дочерние элементы должны именоваться, как sui-checkbox__input

2021-07-08 07:14 UTC, egorka13 commented on src/app/library/components/checkbox/checkbox.component.ts
> +    labelText: string = 'Chechbox';
опечатка

2021-07-08 10:56 UTC, taratatuy commented
Изменен селектор блока компоненты, исправлена опечатка.

2021-07-08 11:08 UTC, egorka13 approved these changes, later dismissed

2021-07-08 14:20 UTC, W014ara approved these changes

2021-07-08 14:32 UTC, egorka13 approved these changes

2021-07-08 14:32 UTC, merged