feature/MSK21QAS create radio component
egorka13/simple-ui-project pull request #8
Opened 2021-07-08 09:49 UTC by izotarina

Реализация компоненты радио-кнопок.
Стили взяты из https://ant.design/components/radio/.
В стилях используются цвета из библиотеки. Как я писала ранее, их добавил Саша в своей ветке. 
Добавила 1 цвет в файл с переменными для текста в состоянии disabled.

2021-07-08 14:30 UTC, taratatuy commented on src/app/library/components/radio/radio.component.html
> +<div class="sui-radio" [class]="typeModifier">
Стили для блока компоненты перенести в :host или превратить этот див в элемент блока: _sui-radio\_\_<...>_.

2021-07-08 14:51 UTC, taratatuy requested changes

2021-07-08 14:51 UTC, taratatuy commented on src/app/library/assets/styles/colors.less
> +@lib-font-disabled: hsla(0deg, 0%, 0%, 25%); // #00000040
Егор замержил этот цвет в деприкейтед, я бы перенес его вниз к актуальным цветам, рядом с _@lib-font-black_.

2021-07-08 14:51 UTC, taratatuy commented on src/app/library/components/radio/radio.component.ts
> +import { Radio } from './radio';
Файлик **radio.ts** переименовать в **radio.model.ts**.

2021-07-08 16:15 UTC, egorka13 requested changes

2021-07-08 16:15 UTC, egorka13 commented on src/app/library/components/radio/radio.ts
> +export interface Radio {
Назови пожалуйста немного подробнее интерфейс, например RadioItem

2021-07-08 16:15 UTC, egorka13 commented on src/app/library/components/radio/radio.component.ts
> +        const labelsArr = this.labels.split(' ');
Не хватает типа

2021-07-11 18:45 UTC, izotarina commented
Исправила все замечания

2021-07-11 19:10 UTC, taratatuy approved these changes

2021-07-11 20:18 UTC, egorka13 approved these changes

2021-07-11 20:19 UTC, merged